// Chatur — Prompt editor: seed presets, strategy + stop-condition catalogs.
window.CHATUR_PROMPTS = {
  strategies: [
    {
      id: "concat",
      name: "Concatenate",
      desc: "Run each prompt sequentially; concatenate raw outputs into one report.",
    },
    {
      id: "reviewer",
      name: "Reviewer",
      desc: "First prompt produces a draft. Following prompts critique and refine it.",
    },
    {
      id: "structured_reviewer",
      name: "Structured Reviewer",
      desc: "Reviewer with a schema. Each pass must emit JSON matching output_schema.",
    },
    {
      id: "schema_merge",
      name: "Schema Merge",
      desc: "Each prompt fills a slice of output_schema. Results are merged by key.",
    },
  ],

  stopConditions: [
    {
      id: "default",
      name: "Strategy default",
      desc: "Use the strategy's built-in halt rule (recommended).",
      text: "",
    },
    {
      id: "finished_token",
      name: "FINISHED token",
      desc: "Append a sentinel rule. Halts the loop on first occurrence.",
      text: "When you have nothing more to add or no further improvements to make, reply with exactly the single token: FINISHED",
    },
    {
      id: "no_new",
      name: "No new findings",
      desc: "Halt when a pass produces no findings not already reported.",
      text: "If this pass would produce no findings beyond those already reported, reply with the single token: FINISHED. Do not repeat earlier findings.",
    },
    {
      id: "confidence",
      name: "High confidence",
      desc: "Halt when the model self-reports confidence above the threshold.",
      text: "After your response, on a new line, write CONFIDENCE: <0–1>. If your confidence is ≥ 0.9 and you have nothing more to add, also write FINISHED on the final line.",
    },
    {
      id: "max_iters",
      name: "Iteration cap (3)",
      desc: "Hard ceiling. Forces a halt after N passes regardless of output.",
      text: "You are on iteration {iter} of 3. On iteration 3, you MUST conclude and reply with FINISHED on the final line, summarizing only the most critical remaining items.",
    },
    {
      id: "schema_complete",
      name: "Schema complete",
      desc: "Halt when every required field of output_schema has a value.",
      text: "Inspect the partial output_schema. If every required field has a non-null value, reply with FINISHED on the final line. Otherwise, fill the next missing field.",
    },
    {
      id: "custom",
      name: "Custom…",
      desc: "Write your own halt rule. Appended verbatim to the prompt.",
      text: "",
    },
  ],

  // Seed presets — what shows in the left rail.
  presets: [
    {
      id: "bugs-default",
      icon: "bug",
      title: "Find Bugs — default",
      desc: "8 prompts · reviewer",
      strategy: "reviewer",
      stopConditionId: "finished_token",
      customStopText: "",
      appendToAll: false,
      output_schema: null,
      builtin: true,
      prompts: [
        "You are a senior engineer reviewing a codebase. Identify potential logic errors, edge cases, and broken assumptions. For each finding, include: file, line range, severity (crit|high|med|low|info), a one-sentence explanation, and a minimal reproduction or fix sketch.",
        "Focus next on error handling. Find every place an error path is swallowed, re-thrown without context, or surfaces as a silent failure. Use the same finding format.",
        "Audit concurrency: races, missing locks, unawaited promises, listeners without cleanup, shared mutable state across async boundaries.",
        "Audit input boundaries: untrusted input reaching SQL, shell, eval, file paths, or deserialization without validation.",
        "Look for state-machine bugs: invalid transitions, missing terminal states, retries without backoff, and replays that aren't idempotent.",
        "Look for resource lifecycle bugs: files/sockets/streams not closed on the error path, timers not cleared, subscriptions not unsubscribed.",
        "Cross-check the findings list. Remove duplicates. Merge findings that point at the same root cause. Re-rank by blast radius × likelihood.",
        "Produce the final report. Group by severity. Inside each group, sort by file. Output only the report.",
      ],
    },
    {
      id: "vulns-owasp",
      icon: "shield",
      title: "Vulnerabilities — OWASP",
      desc: "6 prompts · structured_reviewer",
      strategy: "structured_reviewer",
      stopConditionId: "schema_complete",
      customStopText: "",
      appendToAll: false,
      output_schema: {
        type: "array",
        items: {
          type: "object",
          required: ["category", "severity", "file", "line", "message"],
          properties: {
            category: { type: "string", enum: ["injection","auth","crypto","secrets","ssrf","xss","deserialization","other"] },
            severity: { type: "string", enum: ["crit","high","med","low","info"] },
            file: { type: "string" },
            line: { type: "integer" },
            message: { type: "string" },
            fix: { type: "string" },
          },
        },
      },
      builtin: true,
      prompts: [
        "Scan for injection sinks: SQL, NoSQL, shell, LDAP, template, eval. Emit JSON findings matching the schema. Empty array is valid.",
        "Scan for auth and session handling: missing checks, IDOR, weak cookie flags, JWT misuse, password storage.",
        "Scan for secrets and credentials in source: API keys, tokens, private keys, hardcoded passwords, debug endpoints.",
        "Scan for cryptography misuse: weak algorithms, ECB mode, hardcoded IVs, missing constant-time compares, custom crypto.",
        "Scan for SSRF, open redirect, and unsafe deserialization. Include the dataflow from source → sink in `message`.",
        "Merge all findings. Drop duplicates by (file,line,category). Output the final array.",
      ],
    },
    {
      id: "ideas-product",
      icon: "bulb",
      title: "Generate Ideas",
      desc: "4 prompts · concat",
      strategy: "concat",
      stopConditionId: "default",
      customStopText: "",
      appendToAll: false,
      output_schema: null,
      builtin: true,
      prompts: [
        "Read the README and the top-level routes. Summarize what this product is, who uses it, and what it doesn't do yet.",
        "Brainstorm 10 small, shippable features that would compound the existing UX. One sentence each.",
        "Brainstorm 5 ambitious bets — features that would change what the product is. Be specific about the user behavior they unlock.",
        "Re-read your lists. Drop the boring ones. For the remaining 8, write a one-paragraph pitch each.",
      ],
    },
    {
      id: "refactor-clean",
      icon: "wand",
      title: "Refactor pass",
      desc: "5 prompts · reviewer",
      strategy: "reviewer",
      stopConditionId: "no_new",
      customStopText: "",
      appendToAll: false,
      output_schema: null,
      builtin: true,
      prompts: [
        "Find duplication: copy-pasted blocks > 6 lines, near-duplicate functions, parallel switch statements over the same shape.",
        "Find complexity hotspots: functions > 60 lines, nesting depth > 4, cyclomatic complexity > 10.",
        "Find leaky abstractions: types that pass through 5+ layers, optional-of-optional, booleans that should be enums.",
        "Find naming smells: abbreviations, misleading names, names that lie about return type.",
        "Combine. Output a refactor plan: one named refactor per cluster, ordered by reward/effort.",
      ],
    },
    {
      id: "custom-draft",
      icon: "bookmark",
      title: "Untitled batch",
      desc: "1 prompt · concat",
      strategy: "concat",
      stopConditionId: "default",
      customStopText: "",
      appendToAll: false,
      output_schema: null,
      builtin: false,
      prompts: ["Write your first prompt here…"],
    },
  ],
};
